import { PlaceHolderImages } from '@/lib/placeholder-images';

// --- STAFF DATA (from staff.csv) ---
export const staffData = [
  {
    name: 'Michele Delorit, MD',
    email: 'michele@email.com',
    role: 'General Practicioner',
    location: '111 Medical Road, Suite 24,\nThe Bronx, NY 10467',
    calendarId:
      'Y184OTEyZTBkNzFlNzc0MDgyNTI2MTM1YmJkNWU1NWViMWNhOWE4ZWUwMjNjNzBhMmQxOTNiMjdjZDdkNTc3ZmY5QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20',
    avatarId: 'avatar1',
  },
  {
    name: 'Guoli Hu Johnston, MD',
    email: 'guoli@email.com',
    role: 'General Practicioner',
    location: '111 Medical Road, Suite 24,\nThe Bronx, NY 10467',
    calendarId:
      'Y184OTEyZTBkNzFlNzc0MDgyNTI2MTM1YmJkNWU1NWViMWNhOWE4ZWUwMjNjNzBhMmQxOTNiMjdjZDdkNTc3ZmY5QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20',
    avatarId: 'avatar4',
  },
  {
    name: 'E. Kai Hansen, MD',
    email: 'kai@whitelabeled.ca',
    role: 'General Practicioner',
    location: '2839 Kingsway, Vancouver, BC V5R 5H9, Canada',
    calendarId:
      'c_8912e0d71e774082526135bbd5e55eb1ca9a8ee023c70a2d193b27cd7d577ff9@group.calendar.google.com',
    avatarId: 'avatar3',
  },
  {
    name: 'Sam M. Salama, MD',
    email: 'sam@email.com',
    role: 'General Practicioner',
    location: '111 Medical Road, Suite 24,\nThe Bronx, NY 10467',
    calendarId: '',
    avatarId: 'avatar2',
  },
  {
    name: 'Peter Andrews',
    email: 'peterandrews@email.com',
    role: 'Administrator',
    location: '111 Medical Road, Suite 24,\nThe Bronx, NY 10467',
    calendarId: '',
    avatarId: 'avatar2',
  },
];

// --- CLIENT DATA (from client.csv) ---
export const allClientsData = [
  {
    id: 1,
    name: 'Andrew',
    email: 'Andrew@email.com',
    phone: '16045551212',
    streetAddress: '2831 kingsway',
    city: 'Vancouver',
    province: 'BC',
    postal: 'V5R5H9',
    addictionMedicine: 'Yes',
    treatmentClient: 'No',
    treatmentProvider: 'N/A',
    virtual: 'YES',
    phn: '87654-3210',
    planG: 'Yes',
    narcoticPrescriptions: '',
    insuranceType: 'PPO',
    insuranceMemberId: '27379436432',
    insuranceGroupNo: '12',
    clientId: 'clientId-293845',
    clinicDoctor: 'kai@whitelabeled.ca',
    column1: '',
    avatarId: 'avatar2',
    lastContact: '2024-07-28',
    nextMeeting: '2024-08-05T09:00:00',
  },
  {
    id: 2,
    name: 'David Penny',
    email: 'david@whitelabeled.ca',
    phone: '17789031350',
    streetAddress: '211-316 Cedar Street',
    city: 'New Westminster',
    province: 'BC',
    postal: 'V3L3P1',
    addictionMedicine: 'Yes',
    treatmentClient: 'Yes',
    treatmentProvider: 'TWC',
    virtual: 'Usually',
    phn: '92340-2222',
    planG: 'No',
    narcoticPrescriptions: 'Vyvanse',
    insuranceType: 'Sunlife',
    insuranceMemberId: '1223344',
    insuranceGroupNo: 'G33221',
    clientId: 'clientId-983308',
    clinicDoctor: 'kai@whitelabeled.ca',
    column1: '',
    avatarId: 'avatar3',
    lastContact: '2024-07-25',
    nextMeeting: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'Sarah Lee',
    email: 'sarah.l@gmail.com',
    phone: '12505559876',
    streetAddress: '100 Main St',
    city: 'Victoria',
    province: 'BC',
    postal: 'V8W1A1',
    addictionMedicine: 'No',
    treatmentClient: 'No',
    treatmentProvider: 'N/A',
    virtual: 'YES',
    phn: '73210-9876',
    planG: 'Yes',
    narcoticPrescriptions: '',
    insuranceType: 'Plan G',
    insuranceMemberId: 'Plan G',
    insuranceGroupNo: '',
    clientId: 'clientId-112345',
    clinicDoctor: 'doctor@email.com',
    column1: '',
    avatarId: 'avatar1',
    lastContact: '2024-07-22',
    nextMeeting: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'Robert Smith',
    email: 'rsmith@corp.com',
    phone: '14035552345',
    streetAddress: '45 Railway Ave SW',
    city: 'Calgary',
    province: 'AB',
    postal: 'T2P0X9',
    addictionMedicine: 'Yes',
    treatmentClient: 'Yes',
    treatmentProvider: 'AHS',
    virtual: 'NO',
    phn: '12345-6789',
    planG: 'No',
    narcoticPrescriptions: 'Methadone',
    insuranceType: 'Manulife',
    insuranceMemberId: '55566677788',
    insuranceGroupNo: 'M456',
    clientId: 'clientId-678901',
    clinicDoctor: 'kai@email.com',
    column1: '',
    avatarId: 'avatar2',
    lastContact: '2024-07-20',
    nextMeeting: null,
  },
  {
    id: 5,
    name: 'Jessica Chan',
    email: 'jessica.c@yahoo.ca',
    phone: '16045558888',
    streetAddress: '123 Waterfront Dr',
    city: 'Richmond',
    province: 'BC',
    postal: 'V6X3L3',
    addictionMedicine: 'No',
    treatmentClient: 'No',
    treatmentProvider: 'N/A',
    virtual: 'Usually',
    phn: '34567-8901',
    planG: 'Yes',
    narcoticPrescriptions: '',
    insuranceType: '',
    insuranceMemberId: '',
    insuranceGroupNo: '',
    clientId: 'clientId-334455',
    clinicDoctor: 'doctor@email.com',
    column1: '',
    avatarId: 'avatar4',
    lastContact: '2024-07-30',
    nextMeeting: null,
  },
  {
    id: 6,
    name: 'Michael Brown',
    email: 'mbrown@live.ca',
    phone: '15875551122',
    streetAddress: '800 North Rd',
    city: 'Edmonton',
    province: 'AB',
    postal: 'T5K2R7',
    addictionMedicine: 'Yes',
    treatmentClient: 'No',
    treatmentProvider: 'N/A',
    virtual: 'YES',
    phn: '90123-4567',
    planG: 'No',
    narcoticPrescriptions: '',
    insuranceType: '',
    insuranceMemberId: '',
    insuranceGroupNo: '',
    clientId: 'clientId-778899',
    clinicDoctor: 'kai@email.com',
    column1: '',
    avatarId: 'avatar2',
    lastContact: '2024-07-28',
    nextMeeting: '2024-08-05T09:00:00',
  },
  {
    id: 7,
    name: 'Emily White',
    email: 'ewhite@work.com',
    phone: '13065554321',
    streetAddress: '14 B St. E',
    city: 'Saskatoon',
    province: 'SK',
    postal: 'S7K0P7',
    addictionMedicine: 'No',
    treatmentClient: 'No',
    treatmentProvider: 'N/A',
    virtual: 'NO',
    phn: '56789-0123',
    planG: 'Yes',
    narcoticPrescriptions: '',
    insuranceType: '',
    insuranceMemberId: '',
    insuranceGroupNo: '',
    clientId: 'clientId-210987',
    clinicDoctor: 'doctor@email.com',
    column1: '',
    avatarId: 'avatar1',
    lastContact: '2024-07-25',
    nextMeeting: new Date().toISOString(),
  },
  {
    id: 8,
    name: 'Kevin Green',
    email: 'k.green@mail.com',
    phone: '12045557890',
    streetAddress: '25 Portage Ave',
    city: 'Winnipeg',
    province: 'MB',
    postal: 'R3C0B6',
    addictionMedicine: 'Yes',
    treatmentClient: 'Yes',
    treatmentProvider: 'WPT',
    virtual: 'YES',
    phn: '21098-7654',
    planG: 'No',
    narcoticPrescriptions: 'Fentanyl Patch',
    insuranceType: 'Sunlife',
    insuranceMemberId: '88776655443',
    insuranceGroupNo: 'G22110',
    clientId: 'clientId-543210',
    clinicDoctor: 'kai@email.com',
    column1: '',
    avatarId: 'avatar2',
    lastContact: '2024-07-22',
    nextMeeting: new Date().toISOString(),
  },
  {
    id: 9,
    name: 'Olivia Hall',
    email: 'ohall@outlook.com',
    phone: '19055551000',
    streetAddress: '78 Queen St',
    city: 'Toronto',
    province: 'ON',
    postal: 'M5V2R9',
    addictionMedicine: 'No',
    treatmentClient: 'No',
    treatmentProvider: 'N/A',
    virtual: 'Usually',
    phn: '65432-1098',
    planG: 'Yes',
    narcoticPrescriptions: 'Ativan',
    insuranceType: 'PPO',
    insuranceMemberId: '33221100998',
    insuranceGroupNo: '12',
    clientId: 'clientId-901234',
    clinicDoctor: 'doctor@email.com',
    column1: '',
    avatarId: 'avatar4',
    lastContact: '2024-07-20',
    nextMeeting: null,
  },
  {
    id: 10,
    name: 'William King',
    email: 'billk@whitelabeled.ca',
    phone: '14165552020',
    streetAddress: '150 Financial Blvd',
    city: 'Mississauga',
    province: 'ON',
    postal: 'L5R3G5',
    addictionMedicine: 'Yes',
    treatmentClient: 'No',
    treatmentProvider: 'N/A',
    virtual: 'NO',
    phn: '10987-6543',
    planG: 'No',
    narcoticPrescriptions: '',
    insuranceType: 'Blue Cross',
    insuranceMemberId: '77665544332',
    insuranceGroupNo: 'BC005',
    clientId: 'clientId-876543',
    clinicDoctor: 'kai@email.com',
    column1: '',
    avatarId: 'avatar2',
    lastContact: '2024-07-30',
    nextMeeting: null,
  },
  {
    id: 11,
    name: 'Maria Perez',
    email: 'mperez@hotmail.com',
    phone: '15145553030',
    streetAddress: '300 Rue Sherbrooke',
    city: 'Montreal',
    province: 'QC',
    postal: 'H2L1J6',
    addictionMedicine: 'No',
    treatmentClient: 'No',
    treatmentProvider: 'N/A',
    virtual: 'YES',
    phn: '43210-9876',
    planG: 'Yes',
    narcoticPrescriptions: 'Clonazepam',
    insuranceType: 'Manulife',
    insuranceMemberId: '22110099887',
    insuranceGroupNo: 'M789',
    clientId: 'clientId-456789',
    clinicDoctor: 'doctor@email.com',
    column1: '',
    avatarId: 'avatar1',
    lastContact: '2024-07-28',
    nextMeeting: '2024-08-05T09:00:00',
  },
  {
    id: 12,
    name: 'Ben Carter',
    email: 'bcarter@telus.net',
    phone: '17095554040',
    streetAddress: '5 Water Street',
    city: "St. John's",
    province: 'NL',
    postal: 'A1C6C5',
    addictionMedicine: 'Yes',
    treatmentClient: 'Yes',
    treatmentProvider: 'Solid Ground',
    virtual: 'Usually',
    phn: '89012-3456',
    planG: 'No',
    narcoticPrescriptions: 'Morphine',
    insuranceType: 'Green Shield',
    insuranceMemberId: '66554433221',
    insuranceGroupNo: 'GSC11',
    clientId: 'clientId-109876',
    clinicDoctor: 'kai@email.com',
    column1: '',
    avatarId: 'avatar2',
    lastContact: '2024-07-25',
    nextMeeting: new Date().toISOString(),
  },
  {
    id: 13,
    name: 'Kai Demo',
    email: 'kai@whitelabeled.ca',
    phone: '16044519854',
    streetAddress: '2831 Kingsway, Vancouver, BC V5R 5H9, Canada',
    city: 'Vancouver',
    province: 'British Columbia',
    postal: 'V5R5H9',
    addictionMedicine: 'FALSE',
    treatmentClient: '',
    treatmentProvider: '',
    virtual: 'Yes',
    phn: '74568-2345',
    planG: 'FALSE',
    narcoticPrescriptions: 'None',
    insuranceType: '',
    insuranceMemberId: '',
    insuranceGroupNo: '',
    clientId: 'clientId-demo',
    clinicDoctor: 'kai@whitelabeled.ca',
    column1: '',
    avatarId: 'avatar3',
    lastContact: '2024-07-22',
    nextMeeting: new Date().toISOString(),
  },
];

// --- APPOINTMENTS DATA (from appointments.csv) ---
export const appointmentsData = [
  {
    id: '0.6585030293',
    createdTimestamp: '5/29/2020 12:13:11',
    clientEmail: 'david@whitelabeled.ca',
    staffEmail: 'kai@whitelabeled.ca',
    date: '7/21/2026',
    time: '4299708546',
    meetLink: '',
    status: 'Confirmed',
    clientId: 'clientId-983308',
  },
  {
    id: '0.4224903326',
    createdTimestamp: '5/29/2020 12:34:38',
    clientEmail: 'billk@whitelabeled.ca',
    staffEmail: 'kai@whitelabeled.ca',
    date: '7/21/2025',
    time: '857538116',
    meetLink: '',
    status: '',
    clientId: 'clientId-876543',
  },
  {
    id: 'e00efb2a',
    createdTimestamp: '1/15/2026 14:59:12',
    clientEmail: '',
    staffEmail: 'kai@whitelabeled.ca',
    date: '1/30/2026',
    time: '857538116',
    meetLink: '',
    status: 'Pending',
    clientId: '',
  },
  {
    id: '54ea8477',
    createdTimestamp: '1/15/2026 21:54:43',
    clientEmail: 'kai@whitelabeled.ca',
    staffEmail: '',
    date: '1/18/2026',
    time: '2918390919',
    meetLink: '',
    status: 'Cancelled',
    clientId: '',
  },
];

// --- APPOINTMENT DETAILS (from appointment-details.csv) ---
export const appointmentDetailsData = [
  {
    id: '3e5f083b',
    appointmentId: '0.471461072341743',
    reason: 'I have had a fever and bad cough for over a week now.',
    notes: '',
  },
  {
    id: '26545dfe',
    appointmentId: '0.0265404971418032',
    reason: 'Bad fever',
    notes: '',
  },
  {
    id: '80380bd1',
    appointmentId: '0.944175210016125',
    reason: 'This is a test',
    notes: '',
  },
];

// --- CARE PLAN DATA (from care-plan.csv) ---
export const carePlanData = [
  {
    id: 'e25bce15',
    clientEmail: 'santiagou@google.com',
    staffEmail: 'peter@appsheet.com',
    task: 'Please take 1 aspirin a day for the next 7 days',
    status: 'Complete',
    date: '6/13/2020',
  },
  {
    id: 'c7b382ae',
    clientEmail: 'peter@appsheet.com',
    staffEmail: 'kai@whitelabeled.ca',
    task: 'Remember to take 1 Tylenol a day for 7 days.',
    status: 'Complete',
    date: '6/14/2020',
  },
  {
    id: '606db230',
    clientEmail: 'peter@appsheet.com',
    staffEmail: 'kai@whitelabeled.ca',
    task: 'Drink at least 8 cups of water every day.',
    status: 'Complete',
    date: '6/14/2020',
  },
];

// --- RECORDS DATA (from records.csv) ---
export const recordsData = [
  {
    recordId: '2f983119',
    clientEmail: 'ty@appsheet.com',
    staffEmail: 'michele@email.com',
    type: 'Lab Results',
    record: 'Records_Images/2f983119.Record.110849.png',
    uploadDateTime: '6/6/2020 4:08:31',
  },
  {
    recordId: '2ff0f279',
    clientEmail: 'newuser@email.com',
    staffEmail: 'guoli@email.com',
    type: 'Medications',
    record: '',
    uploadDateTime: '6/6/2020 4:09:01',
  },
  {
    recordId: '130d3dff',
    clientEmail: 'newuser@email.com',
    staffEmail: 'kai@whitelabeled.ca',
    type: 'Lab Results',
    record: 'Records_Files_/130d3dff.Record.185351.pdf',
    uploadDateTime: '6/6/2020 11:53:14',
  },
];

// --- DOCUMENT TEMPLATES DATA (from documents.csv) ---
export const documentTemplatesData = [
  {
    documentId: '682fe33c',
    image:
      'https://fonts.gstatic.com/s/i/googlematerialicons/check_box/v6/gm_grey-48dp/2x/gm_check_box_gm_grey_48dp.png',
    title: 'Patient Registration',
    file: 'Documents_Files_/682fe33c.File.040816.pdf',
    createdTimestamp: '5/17/2020 18:08:11',
  },
  {
    documentId: 'yabdktcy',
    image:
      'https://fonts.gstatic.com/s/i/googlematerialicons/lock_outline/v8/gm_grey-48dp/2x/gm_lock_outline_gm_grey_48dp.png',
    title: 'HIPAA Privacy Notice',
    file: 'Documents_Files_/yabdktcy.File.040759.pdf',
    createdTimestamp: '5/17/2020 18:08:11',
  },
  {
    documentId: 'knd9i4qb',
    image:
      'https://fonts.gstatic.com/s/i/googlematerialicons/security/v6/gm_grey-48dp/2x/gm_security_gm_grey_48dp.png',
    title: 'Patient Information Sheet',
    file: 'Documents_Files_/knd9i4qb.File.040718.pdf',
    createdTimestamp: '5/17/2020 18:08:11',
  },
];

// --- CLIENT DOCUMENTS DATA (from client-documents.csv) ---
export const clientDocumentsData = [
  {
    id: 'd115f669',
    clientEmail: 'newuser@email.com',
    documentId: 'yabdktcy',
    document: 'Client Documents_Files_/d115f669.Document.184852.pdf',
    uploadDateTime: '6/6/2020 11:48:39',
  },
  {
    id: 'b5b52f08',
    clientEmail: 'ohall@outlook.com',
    documentId: '682fe33c',
    document: '',
    uploadDateTime: '1/15/2026 21:56:20',
  },
];

// --- Helper to get upcoming clients for today ---
const today = new Date();
today.setHours(0, 0, 0, 0);
const tomorrow = new Date(today);
tomorrow.setDate(tomorrow.getDate() + 1);

export const upcomingClientsData = allClientsData
  .filter((c) => {
    if (!c.nextMeeting) return false;
    const meetingDate = new Date(c.nextMeeting);
    return meetingDate >= today && meetingDate < tomorrow;
  })
  .map((c) => ({
    ...c,
    time: new Date(c.nextMeeting!).toLocaleTimeString('en-US', {
      hour: 'numeric',
      minute: '2-digit',
    }),
  }));
